export const products = [
  // Chicken Products
  {
    id: 1,
    name: "Fresh Chicken Breast",
    category: "chicken",
    price: 12.99,
    description: "Premium boneless chicken breast, perfect for healthy meals",
    image: "/chicken1.png",
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: "Chicken Thighs",
    category: "chicken",
    price: 9.99,
    description: "Juicy chicken thighs, ideal for grilling and roasting",
    image: "/chicken2.png",
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 3,
    name: "Whole Chicken",
    category: "chicken",
    price: 15.99,
    description: "Fresh whole chicken, perfect for family meals",
    image: "/chicken3.png",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 4,
    name: "Chicken Wings",
    category: "chicken",
    price: 8.99,
    description: "Flavorful chicken wings, great for appetizers",
    image: "/chicken4.png",
    rating: 4.5,
    reviews: 87,
  },
  // Beef Products
  {
    id: 5,
    name: "Premium Beef Steak",
    category: "beef",
    price: 24.99,
    description: "High-quality beef steak, aged for perfect tenderness",
    image: "/beef1.png",
    rating: 4.9,
    reviews: 203,
  },
  {
    id: 6,
    name: "Ground Beef",
    category: "beef",
    price: 11.99,
    description: "Fresh ground beef, perfect for burgers and tacos",
    image: "/beef2.png",
    rating: 4.7,
    reviews: 145,
  },
  {
    id: 7,
    name: "Beef Roast",
    category: "beef",
    price: 22.99,
    description: "Tender beef roast, ideal for slow cooking",
    image: "/beef3.png",
    rating: 4.8,
    reviews: 112,
  },
  {
    id: 8,
    name: "Beef Ribs",
    category: "beef",
    price: 19.99,
    description: "Succulent beef ribs, perfect for BBQ",
    image: "/beef4.png",
    rating: 4.6,
    reviews: 89,
  },
  // Egg Products
  {
    id: 9,
    name: "Free Range Eggs (12)",
    category: "egg",
    price: 6.99,
    description: "Farm-fresh free range eggs, rich in nutrients",
    image: "/egg1.png",
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 10,
    name: "Organic Eggs (18)",
    category: "egg",
    price: 9.99,
    description: "Certified organic eggs from happy hens",
    image: "/egg2.png",
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 11,
    name: "Jumbo Eggs (12)",
    category: "egg",
    price: 7.99,
    description: "Extra large jumbo eggs for hearty breakfasts",
    image: "/egg3.png",
    rating: 4.7,
    reviews: 145,
  },
  {
    id: 12,
    name: "Egg Whites (500ml)",
    category: "egg",
    price: 5.99,
    description: "Pure egg whites, perfect for fitness enthusiasts",
    image: "/egg4.png",
    rating: 4.6,
    reviews: 98,
  },
  // Fish Products
  {
    id: 13,
    name: "Fresh Salmon Fillet",
    category: "fish",
    price: 18.99,
    description: "Premium Atlantic salmon, rich in omega-3",
    image: "/fish1.png",
    rating: 4.9,
    reviews: 267,
  },
  {
    id: 14,
    name: "Tuna Steak",
    category: "fish",
    price: 16.99,
    description: "Fresh tuna steak, perfect for searing",
    image: "/fish2.png",
    rating: 4.8,
    reviews: 134,
  },
  {
    id: 15,
    name: "White Fish Fillet",
    category: "fish",
    price: 12.99,
    description: "Mild white fish, great for baking and frying",
    image: "/fish3.png",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 16,
    name: "Shrimp (500g)",
    category: "fish",
    price: 14.99,
    description: "Fresh jumbo shrimp, peeled and deveined",
    image: "/fish4.png",
    rating: 4.8,
    reviews: 189,
  },
  // Milk Products
  {
    id: 17,
    name: "Whole Milk (1L)",
    category: "milk",
    price: 3.99,
    description: "Fresh whole milk from local farms",
    image: "/milk1.png",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 18,
    name: "Skim Milk (1L)",
    category: "milk",
    price: 3.49,
    description: "Low-fat skim milk, healthy choice",
    image: "/milk2.png",
    rating: 4.6,
    reviews: 245,
  },
  {
    id: 19,
    name: "Organic Milk (1L)",
    category: "milk",
    price: 4.99,
    description: "Certified organic whole milk",
    image: "/milk3.png",
    rating: 4.8,
    reviews: 198,
  },
  {
    id: 20,
    name: "Chocolate Milk (1L)",
    category: "milk",
    price: 4.49,
    description: "Delicious chocolate milk, kids' favorite",
    image: "/milk4.png",
    rating: 4.5,
    reviews: 167,
  },
];

export const categories = [
  { id: "chicken", name: "Chicken", icon: "🍗" },
  { id: "beef", name: "Beef", icon: "🥩" },
  { id: "egg", name: "Eggs", icon: "🥚" },
  { id: "fish", name: "Fish", icon: "🐟" },
  { id: "milk", name: "Milk", icon: "🥛" },
];

export const getProductsByCategory = (category) => {
  return products.filter((product) => product.category === category);
};

export const getProductById = (id) => {
  return products.find((product) => product.id === id);
};
